#!/usr/bin/env python3
import json
import ntpath
import sys
import subprocess
from urllib.parse import quote
from os import path

f = ntpath.basename(sys.argv[1])

process = subprocess.Popen(
    [
        "ffprobe",
        "-v",
        "error",
        "-show_entries",
        "format=duration",
        "-of",
        "default=noprint_wrappers=1:nokey=1",
        f,
    ],
    stdout=subprocess.PIPE,
    universal_newlines=True,
)

output = process.stdout.readline().strip()
output = int(round(float(output), 0))

subs = path.exists(f"{f[0:-4]}.vtt")

template = {
    "title": f[0:-4],
    "duration": output,
    "live": False,
    "sources": [
        {
            "url": f"https://u.nisemo.no/{quote(f)}",
            "contentType": "video/mp4",
            "quality": 1080,
        }
    ],
}

if subs:
    template["textTracks"] = [
        {
            "url": f"https://u.nisemo.no/{quote(f[0:-4])}.vtt",
            "contentType": "text/vtt",
            "name": "English subtitles",
            "default": True,
        }
    ]

with open(f"{f[0:-4]}.json", "w") as outf:
    json.dump(template, outf)

print(f"finished processing {f}")

